### ISSUE TITLE
plugin problems

### ISSUE THREAD

**Issue by damn-good** [brahalla/Cerberus#1]
Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.11:revision (default) on project Cerberus: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml 

how can I do this? I'm new to mvn...

Ok problem solved I had to get the sources using git. Now it's working

**Comment by damn-good** [comment]
I don't get how the database has been configured. where are the config files? can I browse the database using some external tools? please help :-{

**Comment by ghost** [comment]
The database is configured to run in-memory using [H2 DB engine](http://www.h2database.com/html/main.html). Spring Boot creates this in-memory db automatically by looking at the domain objects referenced in the project.
