### ISSUE TITLE
Can't able to find "server.contextPath=/api" in the project A demonstration of a completely stateless and RESTful token-based authorization system using JSON Web Tokens (JWT) and Spring Security.

### ISSUE THREAD

**Issue by NeethuPKrishnan** [brahalla/Cerberus#12]
Whitelabel Error Page when using this http://localhost:8080/api/auth

The below message is occurs.............
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Jun 04 12:59:14 PDT 2016
There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'GET' not supported

Sir, how can i solve this error???

**Comment by ghost** [comment]
This project is an API; you don't use it in a browser. You can use tools like curl or Postman to interact with it.

**Comment by NeethuPKrishnan** [comment]
sir, 
   i have installed postman tool in my chrome browser to interact with the url http://localhost:8080/api/.but the below error occurs.please give me a solution....

{
  "timestamp": 1465412426695,
  "status": 401,
  "error": "Unauthorized",
  "message": "Access Denied",
  "path": "/api/"
}

![error](https://cloud.githubusercontent.com/assets/19743749/15885173/1f703d50-2d0a-11e6-9015-9e2c0a949e7f.PNG)
