### ISSUE TITLE
Can't able to find "server.contextPath=/api" in the project A demonstration of a completely stateless and RESTful token-based authorization system using JSON Web Tokens (JWT) and Spring Security.

### ISSUE THREAD

**Issue by NeethuPKrishnan** [brahalla/Cerberus#14]
sir, 
i have installed postman tool in my chrome browser to interact with the url http://localhost:8080/api/.but the below error occurs.please give me a solution....

{
"timestamp": 1465412426695,
"status": 401,
"error": "Unauthorized",
"message": "Access Denied",
"path": "/api/"
}
![error](https://cloud.githubusercontent.com/assets/19743749/15885202/62af1da2-2d0a-11e6-8b5f-dca206e99f87.PNG)

**Comment by ghost** [comment]
Please read the instructions in the README file. You should be interacting with the authentication endpoint `/api/auth`, sending a POST request with the following JSON content: `{"username":"admin","password":"admin"}`

**Comment by NeethuPKrishnan** [comment]
Sir,
 I have  read the instructions in the README file. But by Postman tool in my chrome browser to interact with the url http://localhost:8080/api/auth  the below error occurs.please give me a solution....
![error2](https://cloud.githubusercontent.com/assets/19743749/15919255/529d4c3a-2dc4-11e6-826c-d91bd132a84a.PNG)

{
  "timestamp": 1465493142926,
  "status": 400,
  "error": "Bad Request",
  "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
  "message": "Required request body is missing: public org.springframework.http.ResponseEntity<?> com.brahalla.Cerberus.controller.rest.AuthenticationController.authenticationRequest(com.brahalla.Cerberus.model.json.request.AuthenticationRequest,org.springframework.mobile.device.Device) throws org.springframework.security.core.AuthenticationException",
  "path": "/api/auth"
}
