### ISSUE TITLE
How to access the claims in the protected controller

### ISSUE THREAD

**Issue by schingeldi** [brahalla/Cerberus#24]
Thanks for the great project. Its really helpful. I have one last question. How do I access the token clains (e.g. username) in the protected controller?

I extended the dummy method a bit and got the username, but I wonder if there is a best practice to get the username in any controller method. Here is what I did:

```
public ResponseEntity<?> getDaHoney(HttpServletRequest request ) {

        String token = request.getHeader(this.tokenHeader);
        String username = this.tokenUtils.getUsernameFromToken(token);
        return ResponseEntity.ok(":O + " + username );
      }
```

**Comment by ghost** [comment]
For accessing stuff that is in the token directly, what you are doing would work. However if you are just wanting the username, authorities, or anything else relevant to spring security then you could just reference the authenticated user for the given request:

```
public ResponseEntity<?> getDaHoney(HttpServletRequest request, Authentication authentication) {
        String username = authentication.getPrincipal().getUsername();
        return ResponseEntity.ok(":O + " + username );
}
```
